name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run tests and generate report
      run: ctest --test-dir build --output-on-failure --output-junit build/test-results.xml

    - name: List build directory contents
      run: ls -la build

    - name: List Testing directory contents
      run: ls -la build/Testing
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: build/test-results.xml
        if-no-files-found: warn
        include-hidden-files: false


  